# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2

commands:
  deploy-firebase:
    description: Deploy to Firebase
    parameters:
      token:
        type: string
        description: Firebase Deploy Token
      alias:
        type: string
        default: "default"
        description: Firebase project alias to deploy to
      only:
        description: Firebase service to deploy on
        type: enum
        enum:
          - hosting
          - functions
        default: hosting
    steps:
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=<< parameters.token >> -P << parameters.alias >> --only << parameters.only >>

jobs:
  test:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm run test
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  deploy:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - deploy-firebase:
          alias: arianee-cert
          token: $FIREBASE_DEPLOY_TOKEN
          only: hosting

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy-approval:
          filters:
            branches:
              only: main
          requires:
            - test
          type: approval
      - deploy:
          requires:
            - deploy-approval
