# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2
  firebase-deploy: azdevs/firebase-deploy@1.0.0

jobs:
  test:
    docker:
      - image: cimg/node:14.17.6-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: test
          command: npm run test
      - persist_to_workspace:
          root: ./
          paths:
            - "*"
  deploy:
    docker:
      - image: cimg/node:14.17.6-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - firebase-deploy/deploy:
          alias: arianee-cert
          token: $FIREBASE_DEPLOY_TOKEN

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy-approval:
          filters:
            branches:
              only: main
          requires:
            - test
          type: approval
      - deploy:
          requires:
            - deploy-approval
